name: "🐛 Bug Report"
description: Report errors or unexpected behavior
labels: 
- Issue-Bug
- Needs-Triage
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/xmha97/PortableApps/issues) before filing a new one!
- type: dropdown
  attributes:
    label: Operating System
    options:
      - Windows 11
      - Windows 10
      - Windows 8.1
      - Windows 8
      - Windows 7
  validations:
    required: true
- type: dropdown
  attributes:
    label: Portable App
    options:
      - ImageGlass Portable
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    placeholder: What is the issue?
  validations:
    required: true
