name: "🐛 Bug report"
description: Report errors or unexpected behavior
labels: 
- Issue-Bug
- Needs-Triage
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/xmha97/PortableApps/issues) before filing a new one!
- type: dropdown
  attributes:
    label: OS
    options:
      - Windows 11
      - Windows 10
      - Windows 8
      - Windows 7
      - Windows Vista
      - Windows XP
  validations:
    required: true
- type: dropdown
  attributes:
    label: App
    options:
      - ImageGlass Portable
      - ScreenToGif Portable
      - Simplenote Portable
      - TextGrab Portable
      - TickTick Portable
      - Trello Portable
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    placeholder: Why do you feel this is incorrect?
  validations:
    required: true
